[package]
name = "lutlib"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "lutlib"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
cxx = "1.0"

[build-dependencies]
cxx-build = "1.0"
